title: DevOps360 (360 Developer Operations)
author: MarkRizzle
email: markrizzle.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 [Platform under construction..]

# social links
github:  DevMarkRizzle.

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
